### ISSUE TITLE
Feedback on frame edit feature branch

### ISSUE THREAD

**Issue by cristofercruz** [HerrZatacke/gb-printer-web#100]
Frameset editing functions are working well on branch **_feature/frameedit-3_**. Here's some feedback on things that can be improved or are missing.

- Frame index field during import should only allow values 1 and greater. Currently it allows a value of 0 which would never get used.
- Import has you specify the ID and index separately but editing a frame after import allows you to change the ID and index as one text field which could lead to invalid inputs for index. Ideally the index would be a number input like during initial import.
- Missing an option to delete a framegroup
- Missing an option to rename a framegroup

Here are a couple mockups for how I could see mentioned changes being laid out.
![frameset-edit](https://user-images.githubusercontent.com/9136454/172252073-fc2286e3-0c95-40b0-b5ec-ddb9d08a69f0.png)
![frame-edit](https://user-images.githubusercontent.com/9136454/172252086-35840412-949b-4f8b-8164-23abb52abfb7.png)

**Comment by HerrZatacke** [comment]
- [x] Frame index field during import should only allow values 1 and greater. Currently it allows a value of 0 which would never get used.
- [x] Import has you specify the ID and index separately but editing a frame after import allows you to change the ID and index as one text field which could lead to invalid inputs for index. Ideally the index would be a number input like during initial import.
- [ ] Missing an option to delete a framegroup
- [ ] Missing an option to rename a framegroup

Technically there is no "Frameset". It's only defined by the character part of the frame-id.
The diplay name of a frameset is always the name of the frame with the lowest index (except for int/jp/hk)

Editing of single frames is now optimized though :-)

**Comment by cristofercruz** [comment]
Good improvements so far! Have some more feedback for you.
- It's still possible to set index 0 using keyboard input. Maybe you can validate this similar to how you validate frameset ID as lowercase/alpha
    - Along those lines would be good to maybe just list that info as help text to avoid questions.
        - Create new frameset with ID (min. 2 chars, alpha, lowercase)
        - Frame index (1 or higher)
- Edit single frame popup isn't doing ID validation. It allows for invalid characters like uppercase, spaces etc.
- The title of the edit single frame popup is the wrong color in light mode, should always be light color text like other popups as the header background is dark on both modes.
- There is inconsistent behavior for frame group dropdown and frame group ID fields between when adding a frame vs editing a frame.
    - Add frame popup disables the ID input field when an existing group is selected and disables the dropdown when the ID field has input. 
    - Edit frame popup keeps both fields always active and when the ID field is set the dropdown auto changes to new group
    - I think the behavior of the edit frame popup is more intuitive as it's easier to switch between using an existing frame group or creating a new one.
- Need consistent naming, add frame popup uses "Frameset", edit frame popup uses "Frame group", I guess I am in favor of the second.
- I can see that a frame group is deleted when all of the last frame in that group is deleted. This makes sense and means we don't need a dedicated delete group option.
- I still think a way to set a display name for a frame group would be helpful. Using the name of the lowest index frame is not ideal as the frame name could be not representative of the whole group. For example I have one group of custom frames and the first name is "1px border black".

**Comment by HerrZatacke** [comment]
> There is inconsistent behavior for frame group dropdown and frame group ID fields between when adding a frame vs editing a frame

Will be difficult to change, because the two forms are generated differently. This would require a bigger re-write of parts of the application

> I still think a way to set a display name for a frame group would be helpful.   

I'll extract this to a separate ToDo once we have the main edit feature implemented and published

**Comment by HerrZatacke** [comment]
> There is inconsistent behavior for frame group dropdown and frame group ID fields between when adding a frame vs editing a frame
Is implemented with the new Import workflow
> I still think a way to set a display name for a frame group would be helpful.
-> https://github.com/HerrZatacke/gb-printer-web/issues/107
