### ISSUE TITLE
Add hello kitty frames

### ISSUE THREAD

**Issue by cristofercruz** [HerrZatacke/gb-printer-web#11]
Add frames from leaked hello kitty camera rom. In doing so, the frame select dropdown might get really messy.
It might make sense to prefix each frame with rom it's from or maybe have a dual dropdowns: one to select rom and second to select the frame. Lastly would need these as an option to select for sav dump imports.

**Comment by HerrZatacke** [comment]
Version 1.7.0 (deployed just now) has the Feature to upload own frames.
This should solve this issue
