### ISSUE TITLE
Display tags in list view rows

### ISSUE THREAD

**Issue by cristofercruz** [HerrZatacke/gb-printer-web#114]
I try to tag my RGB photos to remember which channel each photo corresponds to however, since list view is the only view you can combine RGB photos from and it doesn't display tags it feels like a bit of a guessing game or I need to toggle back and forth between views to get the right order.

Please consider adding tag display to list view. I think there is enough room (especially on desktop), either to the right of the title/date or to the left of the rgb channel selectors.

![tags-in-list](https://user-images.githubusercontent.com/9136454/211692264-f2936df9-aaf0-44b5-8148-758253564b1e.png)

**Comment by HerrZatacke** [comment]
Good point. I will add them in desktop view. In mobile there's just not enough space...
