### ISSUE TITLE
Reduce width on lightbox gallery

### ISSUE THREAD

**Issue by cristofercruz** [HerrZatacke/gb-printer-web#12]
The lighbox gallery popup shows the image too large I think. Could we switch it to use the same width as the editor popup (30rem)? The current large size (calc(95vh - 5rem)) could be kept for when browser full screen mode is active.

**Comment by HerrZatacke** [comment]
I did not completely reduce it down to 30rem (480px) but scaled it down quite a bit (fullscreen remains on 95%)
