### ISSUE TITLE
Dark background for gallery list

### ISSUE THREAD

**Issue by cristofercruz** [HerrZatacke/gb-printer-web#15]
A dark background (#131415?) on the gallery lists would make the photos pop more; right now the lighter background sort of overpowers them.

![consider-dark-list-ui](https://user-images.githubusercontent.com/9136454/97210053-49690380-177a-11eb-9d70-539a33e888ed.png)

**Comment by HerrZatacke** [comment]
Version 1.8.7 featuring a darkmode option:
![2021-02-14_20h59_36](https://user-images.githubusercontent.com/3629415/107887608-8f9fc980-6f07-11eb-9ec6-3882fe4bf63d.png)
