### ISSUE TITLE
Problems backing up and restoring images.

### ISSUE THREAD

**Issue by Mraulio** [HerrZatacke/gb-printer-web#91]
Update : issues happening on Firefox, testing on Chromium for now is OK. 

-I have 1605 images right now on the webapp, and when using the Export images option from the Import tab, and then importing the generated .json on a clean browser, I get 1605 pictures in the Gallery, but around 300 of them have the missing hash error.
![imagen](https://user-images.githubusercontent.com/12874082/170823776-ba65d930-9b82-48aa-bfae-468141e81b8b.png)

-Also, when doing a Backup on Dropbox, the Synchronize to Dropbox option generates 1502 out of 1605 .txt files. Then if I Synchronize from Dropbox, at about the file 1180 I get a Quota has been exceeded error, and never ends the update (no OK button after reaching the 1502 file, 0 images on Gallery).
![imagen](https://user-images.githubusercontent.com/12874082/170823943-349e468b-d916-4c4b-b55d-eb44b55057da.png)
![imagen](https://user-images.githubusercontent.com/12874082/170824921-7e402b25-ab1b-4630-9026-6c33cc4248ab.png)
![imagen](https://user-images.githubusercontent.com/12874082/170824333-71e10f0d-9164-46b6-9454-2b066ca9802e.png)

-When using the Synchronize Images to Dropbox option, it generates the 1605 .jpeg images, having that extension selected on the Settings tab.
![imagen](https://user-images.githubusercontent.com/12874082/170823979-ce5db483-695e-42dd-83c5-efd54b2af68d.png)
![imagen](https://user-images.githubusercontent.com/12874082/170824345-2cef158a-7a23-4871-803c-920696fdcbf7.png)

-The same happens when selecting the 1605 and doing a direct download from the Gallery. If on the settings I have selected .txt Image export filetypes, I get 1502. If I select .jpeg, I get the 1605 images. Having selected .jpeg x1 and .txt files has the same outcome, with 3107 files.

**Comment by HerrZatacke** [comment]
As we found out, this seems to be a Firefox/Quota issue.

For future reference:
Increasing `dom.storage.default_quota` in `about:config` in Firefox can be a workaround for a single user.

Technically, it seems this cannot be "fixed" with this app being "serverless"

In the future a closer look at https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate might be considered to at least warn the user. Currently, the results of the StorageManager API seem to be inconsistent
