### ISSUE TITLE
gameboy camera multi image print

### ISSUE THREAD

**Issue by T0biasCZe** [HerrZatacke/gb-printer-web#94]
The gameboy camera has option to print multiple images at once (Select -> link -> print -> option -> select multiple images) thats allows you to select images, click print, and it will print all of them at once (it transfers one, prints it, transfers second, etc...) until all of them all transfered. but when receiving the image through Web Serial, it imports it as one very long image, not as multiple separate images

**Comment by T0biasCZe** [comment]
![obrazek](https://user-images.githubusercontent.com/44525446/170844335-8b3376dc-fb9f-475c-be9c-b1aa6727eb3a.png)

**Comment by HerrZatacke** [comment]
Did you print with a margin?
Any other value than 0 should create a separate image?
Also, which exact code did you use, and which Arduino(?) are you using?
![image](https://user-images.githubusercontent.com/3629415/171039309-bde079e4-9fe1-4ab0-8876-3843ff3c6696.png)

**Comment by T0biasCZe** [comment]
yeah it was the margin... it prints correctly with line feed
